version: '3.8'

services:
  app-nginx:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: app-nginx
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "81:81"       # Web UI
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"

networks:
  default:           
    name: web-app
    external: true