version: '3.8'
services:
  api:
      container_name: api
      restart: always
      build: ./api
      ports:
        - "3000:3000"
      command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
      volumes:
        - ./api:/app
      depends_on:
      database:
          condition: service_healthy

networks:
  default:           
    name: web-app
    external: true