name: Deploy Directus on EC2 AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy Directus on EC2 AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER

            git clone https://github.com/phongcheat-phus/cicdpipeline.git
            cd /home/${{ secrets.EC2_USER }}/cicdpipeline

            sudo docker network create web-app || true
            cd kong && sudo docker compose up -d --build
            cd ../directus && sudo docker compose up -d --build
