name: Deploy Directus on EC2 AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy Directus on EC2 AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           mkdir /home/${{ secrets.EC2_USER }}/cicdpipeline && cd /home/${{ secrets.EC2_USER }}/cicdpipeline || git clone https://github.com/phongcheat-phus/cicdpipeline.git && cd cicdpipeline
            
            docker network create web-app || true

            cd kong && docker compose up -d --build
            cd ../directus && docker compose up -d --build
