name: Deploy Directus on EC2 AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Directus on EC2 AWS
        uses: appleboy/ssh-action@master
        
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22 
          script: |
            
            cd ./cicdpipeline/api && docker compose up -d --build
            cd ../nginx && docker compose up -d --build
            cd ../kong && sudo rm -rf kong-pg  konga-db  && docker compose up -d --build
            cd ../directus && sudo rm -rf postgres && docker compose up -d --build
            
            
